# This config for django4
# * Sets webserver_type
# * Sets docroot (location of app)
# * specifies postgres db, most common db with django4

webserver_type: nginx-gunicorn

# docroot is where the app is
docroot: "demo"

# postgres seems to be the favorite DB for django4
database:
  type: postgres
  version: "14"

